In [1]:
#Simple Intrest
def simpleintrest(p,t,r):
    print("The Principle amount is{}".format(p))
    print("The Time is {}".format(t))
    print("The rate of intrest is {}".format(r))
    return (p*t*r)/100
print("The Simple Intrest is {}".format(simpleintrest(1000,5,5)))

The Principle amount is1000
The Time is 5
The rate of intrest is 5
The Simple Intrest is 250.0


In [2]:
#Check board
import numpy as np
def check_board(n):
    y = np.ones((n, n)).astype(np.int32)
    y[1::2,::2]=0
    y[::2,1::2]=0
    print(y)
check_board(10)

[[1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]]


In [3]:
def digital_pattern(n):
    for i in n:
        print("/",end=" ")
        print("*"*int(i))
digital_pattern("12345678987654321")

/ *
/ **
/ ***
/ ****
/ *****
/ ******
/ *******
/ ********
/ *********
/ ********
/ *******
/ ******
/ *****
/ ****
/ ***
/ **
/ *


In [4]:
#A = P(1 + R/100) t 
def compound_intrest(p,r,t):
    return (p*(pow((1 + r / 100), t)))-p
compound_intrest(10000, 10.25, 5)

6288.946267774416

In [5]:
# arm strong number
arm=int(input("Enter Number"))
sm=0
for i in str(arm):
    sm+=int(i)**len(str(arm))
if sm==arm:
    print(f"{arm} is arm strong number")
else:
    print(f"{arm} is not armstrong number")

Enter Number153
153 is arm strong number


In [6]:
#Decimalto Binaray
def dec_bin(n):
    binn=""
    while n!=0:
        if n%2!=0:
            binn+="1"
        else:
            binn+="0"
        n=n//2
    binn+="b0"
    return binn[::-1]
#Binary to Decimal
def bin_dec(binary):
    dec,i=0,0
    while binary!=0:
        temp=binary%10
        dec+=temp*(2**i)
        binary//=10
        i+=1
    return dec
binary=1111101000001
integer=8001
print("The Binary of integer {0} is :{1}".format(integer,dec_bin(integer)))
print("The Decimal Number of Binary {0} is :{1}".format(binary,bin_dec(binary)))

The Binary of integer 8001 is :0b1111101000001
The Decimal Number of Binary 1111101000001 is :8001
